// <auto-generated />
using System;
using CraftGame.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CraftGame.Api.Migrations
{
    [DbContext(typeof(CraftGameDbContext))]
    [Migration("20260615163116_AddSessionCompletionStatus")]
    partial class AddSessionCompletionStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CraftGame.Api.Entities.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsStartingElement")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Elements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            Description = "A basic water element",
                            Icon = "💧",
                            IsStartingElement = true,
                            Name = "Water"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            Description = "A basic fire element",
                            Icon = "🔥",
                            IsStartingElement = true,
                            Name = "Fire"
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            Description = "A basic air element",
                            Icon = "💨",
                            IsStartingElement = true,
                            Name = "Air"
                        },
                        new
                        {
                            Id = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            Description = "A basic earth element",
                            Icon = "🌱",
                            IsStartingElement = true,
                            Name = "Earth"
                        },
                        new
                        {
                            Id = new Guid("15d21606-737a-4f8e-81fa-08a439cf407f"),
                            Description = "Wet earth",
                            Icon = "💩",
                            IsStartingElement = false,
                            Name = "Mud"
                        },
                        new
                        {
                            Id = new Guid("24af5e8c-186c-4886-93f4-53171f54045e"),
                            Description = "Hot vapor",
                            Icon = "💨",
                            IsStartingElement = false,
                            Name = "Steam"
                        },
                        new
                        {
                            Id = new Guid("52be66d6-c58a-4379-a53d-d75dfcdaee19"),
                            Description = "Pure power",
                            Icon = "⚡",
                            IsStartingElement = false,
                            Name = "Energy"
                        },
                        new
                        {
                            Id = new Guid("1751b084-2cc8-4abc-9c46-5f915e6e2b79"),
                            Description = "Hard rock",
                            Icon = "🪨",
                            IsStartingElement = false,
                            Name = "Stone"
                        },
                        new
                        {
                            Id = new Guid("cfdfef17-ba96-4c95-8849-ff523e7f2fb1"),
                            Description = "Forged material",
                            Icon = "⛓️",
                            IsStartingElement = false,
                            Name = "Metal"
                        },
                        new
                        {
                            Id = new Guid("5cdaaf70-a9bb-40d9-aff7-6548cd13867c"),
                            Description = "Crafted instrument",
                            Icon = "🛠️",
                            IsStartingElement = false,
                            Name = "Tool"
                        },
                        new
                        {
                            Id = new Guid("399f2f14-ba58-457d-adea-4d6b1cd31b0e"),
                            Description = "Organic material",
                            Icon = "🪵",
                            IsStartingElement = false,
                            Name = "Wood"
                        },
                        new
                        {
                            Id = new Guid("9e2178d5-f5a1-40ef-9341-0b119bb341ec"),
                            Description = "Rolling tool",
                            Icon = "🎡",
                            IsStartingElement = false,
                            Name = "Wheel"
                        },
                        new
                        {
                            Id = new Guid("7c599ff1-2874-46c8-964d-8a2215368c11"),
                            Description = "Machine core",
                            Icon = "⚙️",
                            IsStartingElement = false,
                            Name = "Engine"
                        },
                        new
                        {
                            Id = new Guid("4eda4bc0-da00-43e1-83ed-293a35180476"),
                            Description = "Vehicle",
                            Icon = "🚗",
                            IsStartingElement = false,
                            Name = "Car"
                        },
                        new
                        {
                            Id = new Guid("40e582ff-0317-43a5-83b0-fdc83e2343db"),
                            Description = "The spark of existence",
                            Icon = "✨",
                            IsStartingElement = false,
                            Name = "Life"
                        },
                        new
                        {
                            Id = new Guid("fb802ed3-aaf1-4f35-a98c-2b0b3ca998ff"),
                            Description = "Biological blueprint",
                            Icon = "🧬",
                            IsStartingElement = false,
                            Name = "DNA"
                        },
                        new
                        {
                            Id = new Guid("2811f056-bcda-4dee-aa12-f49235277733"),
                            Description = "Sentient life",
                            Icon = "🧍",
                            IsStartingElement = false,
                            Name = "Human"
                        },
                        new
                        {
                            Id = new Guid("ed102632-5c7b-4246-a60f-65049935ac77"),
                            Description = "Mechanical life",
                            Icon = "🤖",
                            IsStartingElement = false,
                            Name = "Robot"
                        },
                        new
                        {
                            Id = new Guid("c8cb07b9-90c1-48fc-9252-b0334175091b"),
                            Description = "Human-Machine hybrid",
                            Icon = "🦾",
                            IsStartingElement = false,
                            Name = "Cyborg"
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("GoalElementName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "The journey begins. Combine Fire and Water to create Steam.",
                            Difficulty = 1,
                            GoalElementName = "Steam",
                            Name = "Mission: First Vapor",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Earth meets Water. Find Mud.",
                            Difficulty = 1,
                            GoalElementName = "Mud",
                            Name = "Mission: Muddy Path",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Combine Fire and Mud to bake a Stone.",
                            Difficulty = 2,
                            GoalElementName = "Stone",
                            Name = "Mission: Solid Base",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Extreme heat on Stone reveals Metal.",
                            Difficulty = 2,
                            GoalElementName = "Metal",
                            Name = "Mission: Metal Age",
                            Order = 4
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Use Metal and Wood to craft a Tool.",
                            Difficulty = 3,
                            GoalElementName = "Tool",
                            Name = "Mission: Tools of Trade",
                            Order = 5
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "A Tool and Wood create the Wheel.",
                            Difficulty = 3,
                            GoalElementName = "Wheel",
                            Name = "Mission: The Wheel",
                            Order = 6
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Steam power and Metal give birth to the Engine.",
                            Difficulty = 4,
                            GoalElementName = "Engine",
                            Name = "Mission: The Engine",
                            Order = 7
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Description = "Assemble a Car from an Engine and Wheels.",
                            Difficulty = 5,
                            GoalElementName = "Car",
                            Name = "Mission: Transportation",
                            Order = 8
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Description = "Infuse Life into DNA to create a Human.",
                            Difficulty = 6,
                            GoalElementName = "Human",
                            Name = "Mission: Biotechnology",
                            Order = 9
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "The ultimate union. Merge Human and Robot into a Cyborg.",
                            Difficulty = 8,
                            GoalElementName = "Cyborg",
                            Name = "Mission: The Singularity",
                            Order = 10
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.SessionInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("GameSessionId");

                    b.ToTable("SessionInventories");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Email = "playerone@example.com",
                            Username = "PlayerOne"
                        });
                });

            modelBuilder.Entity("LevelStartingElement", b =>
                {
                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.HasKey("ElementId", "LevelId");

                    b.HasIndex("LevelId");

                    b.ToTable("LevelStartingElement");

                    b.HasData(
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ElementId = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            LevelId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ElementId = new Guid("15d21606-737a-4f8e-81fa-08a439cf407f"),
                            LevelId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            ElementId = new Guid("1751b084-2cc8-4abc-9c46-5f915e6e2b79"),
                            LevelId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            ElementId = new Guid("cfdfef17-ba96-4c95-8849-ff523e7f2fb1"),
                            LevelId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            ElementId = new Guid("399f2f14-ba58-457d-adea-4d6b1cd31b0e"),
                            LevelId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            ElementId = new Guid("5cdaaf70-a9bb-40d9-aff7-6548cd13867c"),
                            LevelId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            ElementId = new Guid("399f2f14-ba58-457d-adea-4d6b1cd31b0e"),
                            LevelId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            ElementId = new Guid("24af5e8c-186c-4886-93f4-53171f54045e"),
                            LevelId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            ElementId = new Guid("cfdfef17-ba96-4c95-8849-ff523e7f2fb1"),
                            LevelId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            ElementId = new Guid("7c599ff1-2874-46c8-964d-8a2215368c11"),
                            LevelId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            ElementId = new Guid("9e2178d5-f5a1-40ef-9341-0b119bb341ec"),
                            LevelId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            ElementId = new Guid("40e582ff-0317-43a5-83b0-fdc83e2343db"),
                            LevelId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            ElementId = new Guid("fb802ed3-aaf1-4f35-a98c-2b0b3ca998ff"),
                            LevelId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            ElementId = new Guid("2811f056-bcda-4dee-aa12-f49235277733"),
                            LevelId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            ElementId = new Guid("ed102632-5c7b-4246-a60f-65049935ac77"),
                            LevelId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            ElementId = new Guid("52be66d6-c58a-4379-a53d-d75dfcdaee19"),
                            LevelId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Level", "Level")
                        .WithMany("GameSessions")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.User", "User")
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.SessionInventory", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Element", "Element")
                        .WithMany("Inventories")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.GameSession", "GameSession")
                        .WithMany("InventoryItems")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("LevelStartingElement", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Element", null)
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.Level", null)
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Element", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Level", b =>
                {
                    b.Navigation("GameSessions");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.User", b =>
                {
                    b.Navigation("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
