// <auto-generated />
using System;
using CraftGame.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CraftGame.Api.Migrations
{
    [DbContext(typeof(CraftGameDbContext))]
    [Migration("20260614194410_LevelRedesignAndCleanup")]
    partial class LevelRedesignAndCleanup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CraftGame.Api.Entities.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsStartingElement")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Elements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            Description = "Liquid life",
                            Icon = "💧",
                            IsStartingElement = true,
                            Name = "Water"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            Description = "Burning passion",
                            Icon = "🔥",
                            IsStartingElement = true,
                            Name = "Fire"
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            Description = "Invisible gas",
                            Icon = "💨",
                            IsStartingElement = true,
                            Name = "Air"
                        },
                        new
                        {
                            Id = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            Description = "Solid ground",
                            Icon = "🌱",
                            IsStartingElement = true,
                            Name = "Earth"
                        },
                        new
                        {
                            Id = new Guid("afb2f800-d8ff-443c-8068-6cfd4a6d33cd"),
                            Description = "Organic material",
                            Icon = "🪵",
                            IsStartingElement = false,
                            Name = "Wood"
                        },
                        new
                        {
                            Id = new Guid("567ac8db-1929-47c2-8a91-73ec5d89b81b"),
                            Description = "Heavy metal",
                            Icon = "⛓️",
                            IsStartingElement = false,
                            Name = "Iron"
                        },
                        new
                        {
                            Id = new Guid("b21ea236-2e7c-4936-9763-bd795aa4e5b9"),
                            Description = "The vital spark",
                            Icon = "✨",
                            IsStartingElement = false,
                            Name = "Life"
                        },
                        new
                        {
                            Id = new Guid("8fb9a9ff-55eb-4273-b5c5-d9ceb1b38644"),
                            Description = "Hard rock",
                            Icon = "🪨",
                            IsStartingElement = false,
                            Name = "Stone"
                        },
                        new
                        {
                            Id = new Guid("b1bbd332-f39e-4c73-9a2f-955564a08a61"),
                            Description = "Potential growth",
                            Icon = "🌱",
                            IsStartingElement = false,
                            Name = "Seed"
                        },
                        new
                        {
                            Id = new Guid("2bfb6a22-65af-49e8-b90f-b495fd7a0b23"),
                            Description = "Abstract thought",
                            Icon = "🧠",
                            IsStartingElement = false,
                            Name = "Logic"
                        },
                        new
                        {
                            Id = new Guid("389e82c2-0154-4670-9a6e-66c14f3da6e6"),
                            Description = "Wet earth",
                            Icon = "💩",
                            IsStartingElement = false,
                            Name = "Mud"
                        },
                        new
                        {
                            Id = new Guid("9306f641-61f4-4914-8110-52298f43770d"),
                            Description = "Pure power",
                            Icon = "⚡",
                            IsStartingElement = false,
                            Name = "Energy"
                        },
                        new
                        {
                            Id = new Guid("08ac0228-8db1-4669-aaf2-43713c2b4848"),
                            Description = "Life in the machine",
                            Icon = "🤖",
                            IsStartingElement = false,
                            Name = "AI"
                        },
                        new
                        {
                            Id = new Guid("c3d21c24-e7a2-4558-83b3-5e2ca8160332"),
                            Description = "Vapor power",
                            Icon = "💨",
                            IsStartingElement = false,
                            Name = "Steam"
                        },
                        new
                        {
                            Id = new Guid("c86386bc-ad04-44cf-9eb2-208b4fadfd39"),
                            Description = "Fine particles",
                            Icon = "🌫️",
                            IsStartingElement = false,
                            Name = "Dust"
                        },
                        new
                        {
                            Id = new Guid("e41e62bf-5036-4a3b-9d34-8ea5b95e87fc"),
                            Description = "Burnt wood",
                            Icon = "🌑",
                            IsStartingElement = false,
                            Name = "Charcoal"
                        },
                        new
                        {
                            Id = new Guid("81665166-af36-413d-8657-c1e00d7fee91"),
                            Description = "Strong alloy",
                            Icon = "🛡️",
                            IsStartingElement = false,
                            Name = "Steel"
                        },
                        new
                        {
                            Id = new Guid("78b60ed0-f0aa-4eb1-8e1e-5e2601dd1143"),
                            Description = "Cut wood",
                            Icon = "🪵",
                            IsStartingElement = false,
                            Name = "Plank"
                        },
                        new
                        {
                            Id = new Guid("032d09be-7e8b-4b6e-b662-6488f4863215"),
                            Description = "Steel blade",
                            Icon = "⚔️",
                            IsStartingElement = false,
                            Name = "Sword"
                        },
                        new
                        {
                            Id = new Guid("f12f48ec-32d5-4abc-a01c-a362d3029d5e"),
                            Description = "Green growth",
                            Icon = "🌿",
                            IsStartingElement = false,
                            Name = "Plant"
                        },
                        new
                        {
                            Id = new Guid("8b5ef11f-dd86-4863-a7d5-c7498cab971d"),
                            Description = "Giant plant",
                            Icon = "🌳",
                            IsStartingElement = false,
                            Name = "Tree"
                        },
                        new
                        {
                            Id = new Guid("b58e0aad-2bd6-40f2-8698-79a9119f8271"),
                            Description = "Sea of trees",
                            Icon = "🌲",
                            IsStartingElement = false,
                            Name = "Forest"
                        },
                        new
                        {
                            Id = new Guid("c615e804-8d53-48fa-a335-a67c502bb5a3"),
                            Description = "Source of motion",
                            Icon = "⚙️",
                            IsStartingElement = false,
                            Name = "Engine"
                        },
                        new
                        {
                            Id = new Guid("9269009f-a7ca-4a9f-8d23-ee783cdcccfd"),
                            Description = "Mechanical life",
                            Icon = "🤖",
                            IsStartingElement = false,
                            Name = "Robot"
                        },
                        new
                        {
                            Id = new Guid("62dd35c1-1f68-45e5-a886-994e2d35e12d"),
                            Description = "Cloudy residue",
                            Icon = "🚬",
                            IsStartingElement = false,
                            Name = "Smoke"
                        },
                        new
                        {
                            Id = new Guid("965e9f41-3d2d-4a05-a58b-5880a1aa1749"),
                            Description = "Baked mud",
                            Icon = "🧱",
                            IsStartingElement = false,
                            Name = "Brick"
                        },
                        new
                        {
                            Id = new Guid("ab31d349-3e07-4e95-888b-0a6291b52aeb"),
                            Description = "Living being",
                            Icon = "🐒",
                            IsStartingElement = false,
                            Name = "Creature"
                        },
                        new
                        {
                            Id = new Guid("82143aec-f657-4929-bd8a-3d8d6e190f14"),
                            Description = "Silicone brain",
                            Icon = "🔲",
                            IsStartingElement = false,
                            Name = "Chip"
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("GoalElementName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Start with only Fire. Find Smoke.",
                            Difficulty = 1,
                            GoalElementName = "Smoke",
                            Name = "Mission: Thermal Start",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Water meets Air. Create Steam.",
                            Difficulty = 1,
                            GoalElementName = "Steam",
                            Name = "Mission: The Mist",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Water, Earth, and Fire. Find Mud.",
                            Difficulty = 1,
                            GoalElementName = "Mud",
                            Name = "Mission: Foundation",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Mud, Fire, and Air. Create Brick.",
                            Difficulty = 2,
                            GoalElementName = "Brick",
                            Name = "Mission: Alchemy",
                            Order = 4
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Seed, Water, Earth, and Air. Create a Plant.",
                            Difficulty = 3,
                            GoalElementName = "Plant",
                            Name = "Mission: Botany",
                            Order = 5
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Iron, Wood, and Fire. Forge Steel.",
                            Difficulty = 4,
                            GoalElementName = "Steel",
                            Name = "Mission: Blacksmith",
                            Order = 6
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Steel, Steam, and Logic. Create an Engine.",
                            Difficulty = 5,
                            GoalElementName = "Engine",
                            Name = "Mission: Industry",
                            Order = 7
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Description = "Life, Water, and Earth. Create a Creature.",
                            Difficulty = 6,
                            GoalElementName = "Creature",
                            Name = "Mission: Vitality",
                            Order = 8
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Description = "Energy, Logic, and Iron. Create a Chip.",
                            Difficulty = 7,
                            GoalElementName = "Chip",
                            Name = "Mission: Digital",
                            Order = 9
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Chip, Life, and Steel. Create a Robot.",
                            Difficulty = 8,
                            GoalElementName = "Robot",
                            Name = "Mission: Singularity",
                            Order = 10
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.SessionInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("GameSessionId");

                    b.ToTable("SessionInventories");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Email = "playerone@example.com",
                            Username = "PlayerOne"
                        });
                });

            modelBuilder.Entity("LevelStartingElement", b =>
                {
                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.HasKey("ElementId", "LevelId");

                    b.HasIndex("LevelId");

                    b.ToTable("LevelStartingElement");

                    b.HasData(
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ElementId = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            LevelId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ElementId = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            LevelId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ElementId = new Guid("389e82c2-0154-4670-9a6e-66c14f3da6e6"),
                            LevelId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            ElementId = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            LevelId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            ElementId = new Guid("b1bbd332-f39e-4c73-9a2f-955564a08a61"),
                            LevelId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            ElementId = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            LevelId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            ElementId = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            LevelId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            ElementId = new Guid("567ac8db-1929-47c2-8a91-73ec5d89b81b"),
                            LevelId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            ElementId = new Guid("afb2f800-d8ff-443c-8068-6cfd4a6d33cd"),
                            LevelId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            ElementId = new Guid("81665166-af36-413d-8657-c1e00d7fee91"),
                            LevelId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            ElementId = new Guid("c3d21c24-e7a2-4558-83b3-5e2ca8160332"),
                            LevelId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            ElementId = new Guid("2bfb6a22-65af-49e8-b90f-b495fd7a0b23"),
                            LevelId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            ElementId = new Guid("b21ea236-2e7c-4936-9763-bd795aa4e5b9"),
                            LevelId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            ElementId = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            LevelId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            ElementId = new Guid("9306f641-61f4-4914-8110-52298f43770d"),
                            LevelId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            ElementId = new Guid("2bfb6a22-65af-49e8-b90f-b495fd7a0b23"),
                            LevelId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            ElementId = new Guid("567ac8db-1929-47c2-8a91-73ec5d89b81b"),
                            LevelId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            ElementId = new Guid("08ac0228-8db1-4669-aaf2-43713c2b4848"),
                            LevelId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            ElementId = new Guid("b21ea236-2e7c-4936-9763-bd795aa4e5b9"),
                            LevelId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            ElementId = new Guid("81665166-af36-413d-8657-c1e00d7fee91"),
                            LevelId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Level", "Level")
                        .WithMany("GameSessions")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.User", "User")
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.SessionInventory", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Element", "Element")
                        .WithMany("Inventories")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.GameSession", "GameSession")
                        .WithMany("InventoryItems")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("LevelStartingElement", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Element", null)
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.Level", null)
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Element", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Level", b =>
                {
                    b.Navigation("GameSessions");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.User", b =>
                {
                    b.Navigation("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
