// <auto-generated />
using System;
using CraftGame.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CraftGame.Api.Migrations
{
    [DbContext(typeof(CraftGameDbContext))]
    [Migration("20260507210429_AddMoreSeedDataFinal")]
    partial class AddMoreSeedDataFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CraftGame.Api.Entities.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsStartingElement")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Elements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            Description = "A basic water element",
                            Icon = "💧",
                            IsStartingElement = true,
                            Name = "Water"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            Description = "A basic fire element",
                            Icon = "🔥",
                            IsStartingElement = true,
                            Name = "Fire"
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            Description = "A basic air element",
                            Icon = "💨",
                            IsStartingElement = true,
                            Name = "Air"
                        },
                        new
                        {
                            Id = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            Description = "A basic earth element",
                            Icon = "🌱",
                            IsStartingElement = true,
                            Name = "Earth"
                        },
                        new
                        {
                            Id = new Guid("d1e2f3a4-b5c6-7d8e-9f0a-1b2c3d4e5f6a"),
                            Description = "A hot steam element",
                            Icon = "♨️",
                            IsStartingElement = false,
                            Name = "Steam"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e"),
                            Description = "Wet earth",
                            Icon = "💩",
                            IsStartingElement = false,
                            Name = "Mud"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f"),
                            Description = "Fine particles",
                            Icon = "🌫️",
                            IsStartingElement = false,
                            Name = "Dust"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a"),
                            Description = "Water falling from the sky",
                            Icon = "🌧️",
                            IsStartingElement = false,
                            Name = "Rain"
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<Guid>("GoalElementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GoalElementId");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b"),
                            Description = "Combine elements to create Steam!",
                            Difficulty = 1,
                            GoalElementId = new Guid("d1e2f3a4-b5c6-7d8e-9f0a-1b2c3d4e5f6a"),
                            Name = "The First Step"
                        },
                        new
                        {
                            Id = new Guid("f2a3b4c5-d6e7-8f9a-0b1c-2d3e4f5a6b7c"),
                            Description = "Create Mud and Rain to progress.",
                            Difficulty = 2,
                            GoalElementId = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a"),
                            Name = "Nature's Recipe"
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.SessionInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("GameSessionId");

                    b.ToTable("SessionInventories");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Email = "playerone@example.com",
                            Username = "PlayerOne"
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Level", "Level")
                        .WithMany("GameSessions")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.User", "User")
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Level", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Element", "GoalElement")
                        .WithMany()
                        .HasForeignKey("GoalElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoalElement");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.SessionInventory", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Element", "Element")
                        .WithMany("Inventories")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.GameSession", "GameSession")
                        .WithMany("InventoryItems")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Element", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Level", b =>
                {
                    b.Navigation("GameSessions");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.User", b =>
                {
                    b.Navigation("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
