// <auto-generated />
using System;
using CraftGame.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CraftGame.Api.Migrations
{
    [DbContext(typeof(CraftGameDbContext))]
    [Migration("20260614191328_AddLevelProgression")]
    partial class AddLevelProgression
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CraftGame.Api.Entities.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsStartingElement")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Elements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            Description = "A basic water element",
                            Icon = "💧",
                            IsStartingElement = true,
                            Name = "Water"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            Description = "A basic fire element",
                            Icon = "🔥",
                            IsStartingElement = true,
                            Name = "Fire"
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            Description = "A basic air element",
                            Icon = "💨",
                            IsStartingElement = true,
                            Name = "Air"
                        },
                        new
                        {
                            Id = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            Description = "A basic earth element",
                            Icon = "🌱",
                            IsStartingElement = true,
                            Name = "Earth"
                        },
                        new
                        {
                            Id = new Guid("09c7a812-813f-4ae7-b7fc-e54ab070c650"),
                            Description = "Pure power",
                            Icon = "⚡",
                            IsStartingElement = false,
                            Name = "Energy"
                        },
                        new
                        {
                            Id = new Guid("86c991c9-05e2-48bd-acdc-0e48ca45e8f7"),
                            Description = "Hot vapor",
                            Icon = "💨",
                            IsStartingElement = false,
                            Name = "Steam"
                        },
                        new
                        {
                            Id = new Guid("d44f501d-1895-4f90-b14b-1695bac75ed0"),
                            Description = "Wet earth",
                            Icon = "💩",
                            IsStartingElement = false,
                            Name = "Mud"
                        },
                        new
                        {
                            Id = new Guid("6157c5ca-3655-47a0-81b3-3019e21b3829"),
                            Description = "A fluffy cloud",
                            Icon = "☁️",
                            IsStartingElement = false,
                            Name = "Cloud"
                        },
                        new
                        {
                            Id = new Guid("c77fb0f6-34ad-4140-bf23-c98d2a2b08cc"),
                            Description = "Falling water",
                            Icon = "🌧️",
                            IsStartingElement = false,
                            Name = "Rain"
                        },
                        new
                        {
                            Id = new Guid("2da3ade6-2827-4254-ac44-0ed672300dcd"),
                            Description = "Green life",
                            Icon = "🌿",
                            IsStartingElement = false,
                            Name = "Plant"
                        },
                        new
                        {
                            Id = new Guid("69dc7422-e5bc-4339-9b3c-f50822f6b1d9"),
                            Description = "Boggy waters",
                            Icon = "🐊",
                            IsStartingElement = false,
                            Name = "Swamp"
                        },
                        new
                        {
                            Id = new Guid("0d1856ab-2288-4a02-a064-a1d46625cdca"),
                            Description = "The spark of existence",
                            Icon = "✨",
                            IsStartingElement = false,
                            Name = "Life"
                        },
                        new
                        {
                            Id = new Guid("b51fc042-ed34-4b65-be9f-549a878ae000"),
                            Description = "A living creature",
                            Icon = "🐾",
                            IsStartingElement = false,
                            Name = "Animal"
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("GoalElementName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b"),
                            Description = "Combine Fire and Air to create Energy!",
                            Difficulty = 1,
                            GoalElementName = "Energy",
                            Name = "Mission: The Spark",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("f2a3b4c5-d6e7-8f9a-0b1c-2d3e4f5a6b7c"),
                            Description = "Create Steam from Fire and Water.",
                            Difficulty = 1,
                            GoalElementName = "Steam",
                            Name = "Mission: First Vapor",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("01234567-89ab-cdef-0123-456789abcdef"),
                            Description = "Mix Water and Earth to find Mud.",
                            Difficulty = 1,
                            GoalElementName = "Mud",
                            Name = "Mission: Nature's Foundation",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("fedcba98-7654-3210-fedc-ba9876543210"),
                            Description = "Combine Air and Steam to reach the Clouds.",
                            Difficulty = 2,
                            GoalElementName = "Cloud",
                            Name = "Mission: Skyward",
                            Order = 4
                        },
                        new
                        {
                            Id = new Guid("13fa9943-2d02-4f39-b9f6-e145e62d5d62"),
                            Description = "Find Rain from Water and Clouds.",
                            Difficulty = 2,
                            GoalElementName = "Rain",
                            Name = "Mission: Rain Dance",
                            Order = 5
                        },
                        new
                        {
                            Id = new Guid("11cae710-b744-4b34-a016-a5be5e7be3c4"),
                            Description = "Earth and Rain bring Plants.",
                            Difficulty = 3,
                            GoalElementName = "Plant",
                            Name = "Mission: Growth",
                            Order = 6
                        },
                        new
                        {
                            Id = new Guid("ba9c909d-3d85-4c1c-a3ab-3f200671e7b2"),
                            Description = "Can you find Life in the Swamp?",
                            Difficulty = 4,
                            GoalElementName = "Life",
                            Name = "Mission: Life's Mystery",
                            Order = 7
                        },
                        new
                        {
                            Id = new Guid("dc92f3cb-b82c-406b-828a-04c791c300db"),
                            Description = "An Animal from Life and Earth.",
                            Difficulty = 5,
                            GoalElementName = "Animal",
                            Name = "Mission: The Beast",
                            Order = 8
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.SessionInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("GameSessionId");

                    b.ToTable("SessionInventories");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Email = "playerone@example.com",
                            Username = "PlayerOne"
                        });
                });

            modelBuilder.Entity("LevelStartingElement", b =>
                {
                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.HasKey("ElementId", "LevelId");

                    b.HasIndex("LevelId");

                    b.ToTable("LevelStartingElement");

                    b.HasData(
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("e1f2a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b")
                        },
                        new
                        {
                            ElementId = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            LevelId = new Guid("e1f2a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("f2a3b4c5-d6e7-8f9a-0b1c-2d3e4f5a6b7c")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("f2a3b4c5-d6e7-8f9a-0b1c-2d3e4f5a6b7c")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("01234567-89ab-cdef-0123-456789abcdef")
                        },
                        new
                        {
                            ElementId = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            LevelId = new Guid("01234567-89ab-cdef-0123-456789abcdef")
                        },
                        new
                        {
                            ElementId = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            LevelId = new Guid("fedcba98-7654-3210-fedc-ba9876543210")
                        },
                        new
                        {
                            ElementId = new Guid("86c991c9-05e2-48bd-acdc-0e48ca45e8f7"),
                            LevelId = new Guid("fedcba98-7654-3210-fedc-ba9876543210")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("13fa9943-2d02-4f39-b9f6-e145e62d5d62")
                        },
                        new
                        {
                            ElementId = new Guid("6157c5ca-3655-47a0-81b3-3019e21b3829"),
                            LevelId = new Guid("13fa9943-2d02-4f39-b9f6-e145e62d5d62")
                        },
                        new
                        {
                            ElementId = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            LevelId = new Guid("11cae710-b744-4b34-a016-a5be5e7be3c4")
                        },
                        new
                        {
                            ElementId = new Guid("c77fb0f6-34ad-4140-bf23-c98d2a2b08cc"),
                            LevelId = new Guid("11cae710-b744-4b34-a016-a5be5e7be3c4")
                        },
                        new
                        {
                            ElementId = new Guid("2da3ade6-2827-4254-ac44-0ed672300dcd"),
                            LevelId = new Guid("ba9c909d-3d85-4c1c-a3ab-3f200671e7b2")
                        },
                        new
                        {
                            ElementId = new Guid("d44f501d-1895-4f90-b14b-1695bac75ed0"),
                            LevelId = new Guid("ba9c909d-3d85-4c1c-a3ab-3f200671e7b2")
                        },
                        new
                        {
                            ElementId = new Guid("0d1856ab-2288-4a02-a064-a1d46625cdca"),
                            LevelId = new Guid("dc92f3cb-b82c-406b-828a-04c791c300db")
                        },
                        new
                        {
                            ElementId = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            LevelId = new Guid("dc92f3cb-b82c-406b-828a-04c791c300db")
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Level", "Level")
                        .WithMany("GameSessions")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.User", "User")
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.SessionInventory", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Element", "Element")
                        .WithMany("Inventories")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.GameSession", "GameSession")
                        .WithMany("InventoryItems")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("LevelStartingElement", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Element", null)
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.Level", null)
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Element", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Level", b =>
                {
                    b.Navigation("GameSessions");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.User", b =>
                {
                    b.Navigation("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
