// <auto-generated />
using System;
using CraftGame.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CraftGame.Api.Migrations
{
    [DbContext(typeof(CraftGameDbContext))]
    [Migration("20260614195444_PlayableLevelDesign")]
    partial class PlayableLevelDesign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CraftGame.Api.Entities.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsStartingElement")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Elements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            Description = "A basic water element",
                            Icon = "💧",
                            IsStartingElement = true,
                            Name = "Water"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            Description = "A basic fire element",
                            Icon = "🔥",
                            IsStartingElement = true,
                            Name = "Fire"
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            Description = "A basic air element",
                            Icon = "💨",
                            IsStartingElement = true,
                            Name = "Air"
                        },
                        new
                        {
                            Id = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            Description = "A basic earth element",
                            Icon = "🌱",
                            IsStartingElement = true,
                            Name = "Earth"
                        },
                        new
                        {
                            Id = new Guid("7bc855bd-5e73-4b78-8230-eb7d9f30f2a1"),
                            Description = "Wet earth",
                            Icon = "💩",
                            IsStartingElement = false,
                            Name = "Mud"
                        },
                        new
                        {
                            Id = new Guid("cd7f6f66-d9b0-4d52-9d47-3915235a0cf8"),
                            Description = "Hot vapor",
                            Icon = "💨",
                            IsStartingElement = false,
                            Name = "Steam"
                        },
                        new
                        {
                            Id = new Guid("0d367258-b056-4a63-b15d-441e3940feaf"),
                            Description = "Pure power",
                            Icon = "⚡",
                            IsStartingElement = false,
                            Name = "Energy"
                        },
                        new
                        {
                            Id = new Guid("37cf0b28-ecd2-4fc2-b758-83f21ca0e247"),
                            Description = "Hard rock",
                            Icon = "🪨",
                            IsStartingElement = false,
                            Name = "Stone"
                        },
                        new
                        {
                            Id = new Guid("fe8356fa-a630-479a-bd4b-55b35974d9d9"),
                            Description = "Forged material",
                            Icon = "⛓️",
                            IsStartingElement = false,
                            Name = "Metal"
                        },
                        new
                        {
                            Id = new Guid("27b7f07c-f5f8-434e-be87-2414d120759c"),
                            Description = "Crafted instrument",
                            Icon = "🛠️",
                            IsStartingElement = false,
                            Name = "Tool"
                        },
                        new
                        {
                            Id = new Guid("1e70e58b-c328-4a04-be4f-a2c16aae14eb"),
                            Description = "Organic material",
                            Icon = "🪵",
                            IsStartingElement = false,
                            Name = "Wood"
                        },
                        new
                        {
                            Id = new Guid("306c2345-be15-4fa4-8e2f-1dfe8d792643"),
                            Description = "Rolling tool",
                            Icon = "🎡",
                            IsStartingElement = false,
                            Name = "Wheel"
                        },
                        new
                        {
                            Id = new Guid("a0f88725-69f2-462b-ace8-ac6a51e7d51b"),
                            Description = "Machine core",
                            Icon = "⚙️",
                            IsStartingElement = false,
                            Name = "Engine"
                        },
                        new
                        {
                            Id = new Guid("4e963255-ddfb-447d-b0e6-0237271f8d1d"),
                            Description = "Vehicle",
                            Icon = "🚗",
                            IsStartingElement = false,
                            Name = "Car"
                        },
                        new
                        {
                            Id = new Guid("a60f7fcc-619a-4242-b369-3f8be35cac4e"),
                            Description = "The spark of existence",
                            Icon = "✨",
                            IsStartingElement = false,
                            Name = "Life"
                        },
                        new
                        {
                            Id = new Guid("e680e741-81cd-4a3a-a7a1-8ec8671b746c"),
                            Description = "Biological blueprint",
                            Icon = "🧬",
                            IsStartingElement = false,
                            Name = "DNA"
                        },
                        new
                        {
                            Id = new Guid("d7cace2b-6a2b-4a76-8da8-78561e18ed87"),
                            Description = "Sentient life",
                            Icon = "🧍",
                            IsStartingElement = false,
                            Name = "Human"
                        },
                        new
                        {
                            Id = new Guid("6e27bc6a-9790-4ddb-8b2b-1d68349544dd"),
                            Description = "Mechanical life",
                            Icon = "🤖",
                            IsStartingElement = false,
                            Name = "Robot"
                        },
                        new
                        {
                            Id = new Guid("205734b2-0254-4e7f-b095-b8ac49bd5c4b"),
                            Description = "Human-Machine hybrid",
                            Icon = "🦾",
                            IsStartingElement = false,
                            Name = "Cyborg"
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("GoalElementName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "The journey begins. Combine Fire and Water to create Steam.",
                            Difficulty = 1,
                            GoalElementName = "Steam",
                            Name = "Mission: First Vapor",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Earth meets Water. Find Mud.",
                            Difficulty = 1,
                            GoalElementName = "Mud",
                            Name = "Mission: Muddy Path",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Combine Fire and Mud to bake a Stone.",
                            Difficulty = 2,
                            GoalElementName = "Stone",
                            Name = "Mission: Solid Base",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Extreme heat on Stone reveals Metal.",
                            Difficulty = 2,
                            GoalElementName = "Metal",
                            Name = "Mission: Metal Age",
                            Order = 4
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Use Metal and Wood to craft a Tool.",
                            Difficulty = 3,
                            GoalElementName = "Tool",
                            Name = "Mission: Tools of Trade",
                            Order = 5
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "A Tool and Wood create the Wheel.",
                            Difficulty = 3,
                            GoalElementName = "Wheel",
                            Name = "Mission: The Wheel",
                            Order = 6
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Steam power and Metal give birth to the Engine.",
                            Difficulty = 4,
                            GoalElementName = "Engine",
                            Name = "Mission: The Engine",
                            Order = 7
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Description = "Assemble a Car from an Engine and Wheels.",
                            Difficulty = 5,
                            GoalElementName = "Car",
                            Name = "Mission: Transportation",
                            Order = 8
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Description = "Infuse Life into DNA to create a Human.",
                            Difficulty = 6,
                            GoalElementName = "Human",
                            Name = "Mission: Biotechnology",
                            Order = 9
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "The ultimate union. Merge Human and Robot into a Cyborg.",
                            Difficulty = 8,
                            GoalElementName = "Cyborg",
                            Name = "Mission: The Singularity",
                            Order = 10
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.SessionInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("GameSessionId");

                    b.ToTable("SessionInventories");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Email = "playerone@example.com",
                            Username = "PlayerOne"
                        });
                });

            modelBuilder.Entity("LevelStartingElement", b =>
                {
                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.HasKey("ElementId", "LevelId");

                    b.HasIndex("LevelId");

                    b.ToTable("LevelStartingElement");

                    b.HasData(
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ElementId = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            LevelId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ElementId = new Guid("7bc855bd-5e73-4b78-8230-eb7d9f30f2a1"),
                            LevelId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            ElementId = new Guid("37cf0b28-ecd2-4fc2-b758-83f21ca0e247"),
                            LevelId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            ElementId = new Guid("fe8356fa-a630-479a-bd4b-55b35974d9d9"),
                            LevelId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            ElementId = new Guid("1e70e58b-c328-4a04-be4f-a2c16aae14eb"),
                            LevelId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            ElementId = new Guid("27b7f07c-f5f8-434e-be87-2414d120759c"),
                            LevelId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            ElementId = new Guid("1e70e58b-c328-4a04-be4f-a2c16aae14eb"),
                            LevelId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            ElementId = new Guid("cd7f6f66-d9b0-4d52-9d47-3915235a0cf8"),
                            LevelId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            ElementId = new Guid("fe8356fa-a630-479a-bd4b-55b35974d9d9"),
                            LevelId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            ElementId = new Guid("a0f88725-69f2-462b-ace8-ac6a51e7d51b"),
                            LevelId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            ElementId = new Guid("306c2345-be15-4fa4-8e2f-1dfe8d792643"),
                            LevelId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            ElementId = new Guid("a60f7fcc-619a-4242-b369-3f8be35cac4e"),
                            LevelId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            ElementId = new Guid("e680e741-81cd-4a3a-a7a1-8ec8671b746c"),
                            LevelId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            ElementId = new Guid("d7cace2b-6a2b-4a76-8da8-78561e18ed87"),
                            LevelId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            ElementId = new Guid("6e27bc6a-9790-4ddb-8b2b-1d68349544dd"),
                            LevelId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            ElementId = new Guid("0d367258-b056-4a63-b15d-441e3940feaf"),
                            LevelId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Level", "Level")
                        .WithMany("GameSessions")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.User", "User")
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.SessionInventory", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Element", "Element")
                        .WithMany("Inventories")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.GameSession", "GameSession")
                        .WithMany("InventoryItems")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("LevelStartingElement", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Element", null)
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.Level", null)
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Element", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Level", b =>
                {
                    b.Navigation("GameSessions");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.User", b =>
                {
                    b.Navigation("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
