// <auto-generated />
using System;
using CraftGame.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CraftGame.Api.Migrations
{
    [DbContext(typeof(CraftGameDbContext))]
    [Migration("20260614193400_UpdateComplexLevels")]
    partial class UpdateComplexLevels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CraftGame.Api.Entities.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsStartingElement")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Elements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            Description = "Liquid life",
                            Icon = "💧",
                            IsStartingElement = true,
                            Name = "Water"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            Description = "Burning passion",
                            Icon = "🔥",
                            IsStartingElement = true,
                            Name = "Fire"
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            Description = "Invisible gas",
                            Icon = "💨",
                            IsStartingElement = true,
                            Name = "Air"
                        },
                        new
                        {
                            Id = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            Description = "Solid ground",
                            Icon = "🌱",
                            IsStartingElement = true,
                            Name = "Earth"
                        },
                        new
                        {
                            Id = new Guid("6c9abfdd-58dd-4d02-8753-b310e6fe4494"),
                            Description = "Pure power",
                            Icon = "⚡",
                            IsStartingElement = false,
                            Name = "Energy"
                        },
                        new
                        {
                            Id = new Guid("59520af8-9bec-4926-8b69-ffa3d7a95441"),
                            Description = "Hot vapor",
                            Icon = "💨",
                            IsStartingElement = false,
                            Name = "Steam"
                        },
                        new
                        {
                            Id = new Guid("47809f17-565e-4ed5-bc5a-2ba4b3659d4d"),
                            Description = "Wet earth",
                            Icon = "💩",
                            IsStartingElement = false,
                            Name = "Mud"
                        },
                        new
                        {
                            Id = new Guid("a3da2fb0-4df6-4d9c-857e-2662ecc5106b"),
                            Description = "Fluffy vapor",
                            Icon = "☁️",
                            IsStartingElement = false,
                            Name = "Cloud"
                        },
                        new
                        {
                            Id = new Guid("34679d83-ba1b-4d52-85c2-bd53eca97d76"),
                            Description = "Falling water",
                            Icon = "🌧️",
                            IsStartingElement = false,
                            Name = "Rain"
                        },
                        new
                        {
                            Id = new Guid("9a208dbd-460c-4a31-9d60-8563d8ec73c4"),
                            Description = "Green life",
                            Icon = "🌿",
                            IsStartingElement = false,
                            Name = "Plant"
                        },
                        new
                        {
                            Id = new Guid("0754c578-ba64-4223-ad30-fbbc66bfa20d"),
                            Description = "Boggy waters",
                            Icon = "🐊",
                            IsStartingElement = false,
                            Name = "Swamp"
                        },
                        new
                        {
                            Id = new Guid("22a6cd60-3078-492f-93cd-1094c4b1ccde"),
                            Description = "The spark of existence",
                            Icon = "✨",
                            IsStartingElement = false,
                            Name = "Life"
                        },
                        new
                        {
                            Id = new Guid("587c4e21-4181-4939-8995-3c8234dac9ee"),
                            Description = "Living creature",
                            Icon = "🐾",
                            IsStartingElement = false,
                            Name = "Animal"
                        },
                        new
                        {
                            Id = new Guid("8db87892-1f42-4d00-81c9-746af9d46279"),
                            Description = "Sticky mud",
                            Icon = "🏺",
                            IsStartingElement = false,
                            Name = "Clay"
                        },
                        new
                        {
                            Id = new Guid("d9c6bb01-be41-4af6-9bbd-ab74527d4aa1"),
                            Description = "Baked clay",
                            Icon = "🧱",
                            IsStartingElement = false,
                            Name = "Brick"
                        },
                        new
                        {
                            Id = new Guid("ea38bc03-983e-4761-8b91-cac510f6a276"),
                            Description = "Stacked bricks",
                            Icon = "🧱",
                            IsStartingElement = false,
                            Name = "Wall"
                        },
                        new
                        {
                            Id = new Guid("4954f32e-8666-4e6b-9883-05408e18fb7a"),
                            Description = "A place to live",
                            Icon = "🏠",
                            IsStartingElement = false,
                            Name = "House"
                        },
                        new
                        {
                            Id = new Guid("8ded38e8-64b0-4175-855b-247c877bc2fc"),
                            Description = "Forged earth",
                            Icon = "⛓️",
                            IsStartingElement = false,
                            Name = "Metal"
                        },
                        new
                        {
                            Id = new Guid("a60583bb-584e-48aa-b6a1-10243c5aa6e2"),
                            Description = "Helpful object",
                            Icon = "🛠️",
                            IsStartingElement = false,
                            Name = "Tool"
                        },
                        new
                        {
                            Id = new Guid("2c9cbdb5-845b-4d25-94f8-0ae56a4073af"),
                            Description = "Rolling tool",
                            Icon = "🎡",
                            IsStartingElement = false,
                            Name = "Wheel"
                        },
                        new
                        {
                            Id = new Guid("c2715e07-56e8-48f9-aa7b-04da4016ab2e"),
                            Description = "Metal on wheels",
                            Icon = "🚗",
                            IsStartingElement = false,
                            Name = "Car"
                        },
                        new
                        {
                            Id = new Guid("7c198daf-f671-4bdb-a263-b2dc9f29a570"),
                            Description = "Directed energy",
                            Icon = "💡",
                            IsStartingElement = false,
                            Name = "Electricity"
                        },
                        new
                        {
                            Id = new Guid("7ac00b3e-2ad5-46c7-9ed9-d919a2e9f4e8"),
                            Description = "Metal and electricity",
                            Icon = "💻",
                            IsStartingElement = false,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = new Guid("100ca108-27ab-43af-962c-b11fcb394a8a"),
                            Description = "Life in the machine",
                            Icon = "🤖",
                            IsStartingElement = false,
                            Name = "AI"
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("GoalElementName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b"),
                            Description = "Create Energy to begin the industrial age.",
                            Difficulty = 1,
                            GoalElementName = "Energy",
                            Name = "Mission: The Spark",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("f2a3b4c5-d6e7-8f9a-0b1c-2d3e4f5a6b7c"),
                            Description = "Find the recipe for a Plant.",
                            Difficulty = 2,
                            GoalElementName = "Plant",
                            Name = "Mission: Basic Life",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("01234567-89ab-cdef-0123-456789abcdef"),
                            Description = "Build a House from the ground up.",
                            Difficulty = 3,
                            GoalElementName = "House",
                            Name = "Mission: Construction",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("fedcba98-7654-3210-fedc-ba9876543210"),
                            Description = "Create an Animal from the primordial swamp.",
                            Difficulty = 4,
                            GoalElementName = "Animal",
                            Name = "Mission: Evolution",
                            Order = 4
                        },
                        new
                        {
                            Id = new Guid("170effd3-724e-493c-a10a-06c7733ad8b6"),
                            Description = "Invent the Wheel to change everything.",
                            Difficulty = 5,
                            GoalElementName = "Wheel",
                            Name = "Mission: Mechanics",
                            Order = 5
                        },
                        new
                        {
                            Id = new Guid("3bdaf10f-3b91-48f6-9a78-281ebc0b606b"),
                            Description = "Assemble a Car from metal and motion.",
                            Difficulty = 6,
                            GoalElementName = "Car",
                            Name = "Mission: Transport",
                            Order = 6
                        },
                        new
                        {
                            Id = new Guid("0f7a44b9-e5d1-43ee-8ce7-5b4d22074ef9"),
                            Description = "Construct a Computer from logic and metal.",
                            Difficulty = 7,
                            GoalElementName = "Computer",
                            Name = "Mission: Digital Age",
                            Order = 7
                        },
                        new
                        {
                            Id = new Guid("faa2522e-7259-4f51-b313-d3e23a05efba"),
                            Description = "Bring AI to life within the machine.",
                            Difficulty = 8,
                            GoalElementName = "AI",
                            Name = "Mission: Singularity",
                            Order = 8
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.SessionInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("GameSessionId");

                    b.ToTable("SessionInventories");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Email = "playerone@example.com",
                            Username = "PlayerOne"
                        });
                });

            modelBuilder.Entity("LevelStartingElement", b =>
                {
                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.HasKey("ElementId", "LevelId");

                    b.HasIndex("LevelId");

                    b.ToTable("LevelStartingElement");

                    b.HasData(
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("e1f2a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("e1f2a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b")
                        },
                        new
                        {
                            ElementId = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            LevelId = new Guid("e1f2a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b")
                        },
                        new
                        {
                            ElementId = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            LevelId = new Guid("e1f2a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("f2a3b4c5-d6e7-8f9a-0b1c-2d3e4f5a6b7c")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("f2a3b4c5-d6e7-8f9a-0b1c-2d3e4f5a6b7c")
                        },
                        new
                        {
                            ElementId = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            LevelId = new Guid("f2a3b4c5-d6e7-8f9a-0b1c-2d3e4f5a6b7c")
                        },
                        new
                        {
                            ElementId = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            LevelId = new Guid("f2a3b4c5-d6e7-8f9a-0b1c-2d3e4f5a6b7c")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("01234567-89ab-cdef-0123-456789abcdef")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("01234567-89ab-cdef-0123-456789abcdef")
                        },
                        new
                        {
                            ElementId = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            LevelId = new Guid("01234567-89ab-cdef-0123-456789abcdef")
                        },
                        new
                        {
                            ElementId = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            LevelId = new Guid("01234567-89ab-cdef-0123-456789abcdef")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("fedcba98-7654-3210-fedc-ba9876543210")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("fedcba98-7654-3210-fedc-ba9876543210")
                        },
                        new
                        {
                            ElementId = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            LevelId = new Guid("fedcba98-7654-3210-fedc-ba9876543210")
                        },
                        new
                        {
                            ElementId = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            LevelId = new Guid("fedcba98-7654-3210-fedc-ba9876543210")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("170effd3-724e-493c-a10a-06c7733ad8b6")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("170effd3-724e-493c-a10a-06c7733ad8b6")
                        },
                        new
                        {
                            ElementId = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            LevelId = new Guid("170effd3-724e-493c-a10a-06c7733ad8b6")
                        },
                        new
                        {
                            ElementId = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            LevelId = new Guid("170effd3-724e-493c-a10a-06c7733ad8b6")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("3bdaf10f-3b91-48f6-9a78-281ebc0b606b")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("3bdaf10f-3b91-48f6-9a78-281ebc0b606b")
                        },
                        new
                        {
                            ElementId = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            LevelId = new Guid("3bdaf10f-3b91-48f6-9a78-281ebc0b606b")
                        },
                        new
                        {
                            ElementId = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            LevelId = new Guid("3bdaf10f-3b91-48f6-9a78-281ebc0b606b")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("0f7a44b9-e5d1-43ee-8ce7-5b4d22074ef9")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("0f7a44b9-e5d1-43ee-8ce7-5b4d22074ef9")
                        },
                        new
                        {
                            ElementId = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            LevelId = new Guid("0f7a44b9-e5d1-43ee-8ce7-5b4d22074ef9")
                        },
                        new
                        {
                            ElementId = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            LevelId = new Guid("0f7a44b9-e5d1-43ee-8ce7-5b4d22074ef9")
                        },
                        new
                        {
                            ElementId = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            LevelId = new Guid("faa2522e-7259-4f51-b313-d3e23a05efba")
                        },
                        new
                        {
                            ElementId = new Guid("c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f"),
                            LevelId = new Guid("faa2522e-7259-4f51-b313-d3e23a05efba")
                        },
                        new
                        {
                            ElementId = new Guid("f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c"),
                            LevelId = new Guid("faa2522e-7259-4f51-b313-d3e23a05efba")
                        },
                        new
                        {
                            ElementId = new Guid("a2b3c4d5-e6f7-8a9b-0c1d-2e3f4a5b6c7d"),
                            LevelId = new Guid("faa2522e-7259-4f51-b313-d3e23a05efba")
                        });
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Level", "Level")
                        .WithMany("GameSessions")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.User", "User")
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.SessionInventory", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Element", "Element")
                        .WithMany("Inventories")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.GameSession", "GameSession")
                        .WithMany("InventoryItems")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("LevelStartingElement", b =>
                {
                    b.HasOne("CraftGame.Api.Entities.Element", null)
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftGame.Api.Entities.Level", null)
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Element", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.GameSession", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.Level", b =>
                {
                    b.Navigation("GameSessions");
                });

            modelBuilder.Entity("CraftGame.Api.Entities.User", b =>
                {
                    b.Navigation("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
